[user]
key = "~/.ssh/id_rsa"

[forks]
  [forks.kubernetes]
  upstream = "git@github.com:kubernetes/kubernetes.git"
  fork = "git@github.com:topikettunen/kubernetes.git"

  [forks.sbcl]
  upstream = "git@github.com:sbcl/sbcl.git"
  fork = "git@github.com:topikettunen/sbcl.git"
